[tools]
bun = "latest"
node = "lts"
uv = "latest"
ruff = "latest"
ruby = "latest"
java = "lts"
go = "latest"
erlang = "27"
elixir = "1.18-otp-27"

lua-language-server = "latest"
taplo = "latest"
elixir-ls = "latest"

"npm:npm" = "latest"
"npm:yarn" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:marked" = "latest"
"npm:opencode-ai" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:tree-sitter-cli" = "latest"

"ubi:iwe-org/iwe" = { version = "latest", extract_all = true }
"ubi:git-town/git-town" = "latest"
"ubi:thomasschafer/scooter" = "latest"
"ubi:elixir-lang/expert" = "nightly"

"pipx:basedpyright" = "latest"
"pipx:pyinfra" = "latest"
"pipx:aider-chat" = "latest"

"gem:rails" = "latest"
"gem:ruby-lsp" = "latest"

"go:github.com/air-verse/air" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "postgres" }
"go:github.com/melkeydev/go-blueprint" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"

dotnet = "10.0.100-rc.1.25451.107"

ripgrep = "latest"
fd = "latest"
neovim = "latest"
tmux = "latest"
starship = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[settings.pipx]
uvx = true
