theme = "transparent"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
bufferline = "multiple"
scrolloff = 10
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = false

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "diagnostics",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "selections",
  "primary-selection-length",
  "position",
  "position-percentage",
  "total-line-numbers",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[keys.normal]
X = "select_line_above"
x = "select_line_below"
C-c = ":buffer-close"
C-s = ":write"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-h = "unindent"
C-l = "indent"
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
ret = "goto_word"
A-g = [":new", ":insert-output lazygit >/dev/tty", ":buffer-close!", ":redraw"]
A-y = [
  ":new",
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":buffer-close!",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":open %sh{cat /tmp/unique-file-h21a434}",
]
A-r = [":new", ":insert-output scooter >/dev/tty", ":buffer-close!", ":redraw"]
C-r = ":reload-all"
C-m = ":sh ~/.scripts/commit-message-generator"
"=" = ":format"
A-z = "suspend"
G = "goto_file_end"

[keys.select]
G = "extend_to_file_end"

[keys.insert]
C-h = "move_char_left"
C-j = "move_line_down"
C-k = "move_line_up"
C-l = "move_char_right"
tab = "inline_completion_accept"
esc = "inline_completion_dismiss"
C-n = "inline_completion_next"
C-p = "inline_completion_prev"
C-space = "inline_completion_trigger"

[keys.normal.-]
d = ":cd %sh{echo $DOTFILES}"
h = ":cd %sh{echo $HOME}"
- = ":cd %sh{echo $OLDPWD}"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
#newline = "⏎"
tabpad = "·"  

[editor.file-picker]
hidden = false

